// ════════════════════════════════════════════════════════════════
// scripts/gen-seed.mjs — regenerate seed.sql from a saved copy of
// the source page, using the exact parser the Worker runs.
//
//   node scripts/gen-seed.mjs <saved-page.html> > seed.sql
//
// Why a saved file rather than a live fetch: sports.gov.tw sits
// behind a Cloudflare bot challenge, so a plain HTTP client gets a
// 403 "Just a moment..." page. Save the rendered HTML from a real
// browser first (View Source / DevTools → Copy outerHTML).
//
// Requires Node ≥ 22 for native TypeScript type stripping.
// ════════════════════════════════════════════════════════════════

import { readFileSync } from "node:fs";
import { deterministicId, dedupe, parseCoaches } from "../worker/parse.ts";

const file = process.argv[2];
if (!file) {
  console.error("usage: node scripts/gen-seed.mjs <saved-page.html> > seed.sql");
  process.exit(1);
}

const html = readFileSync(file, "utf8");
const { coaches, via } = parseCoaches(html);
const rows = dedupe(coaches);

if (rows.length === 0) {
  console.error(`no records parsed from ${file} (via=${via})`);
  process.exit(1);
}

const missing = rows.filter((c) => !c.judgmentUrl).length;
console.error(`parsed ${rows.length} records via ${via}; ${missing} without a judgment URL`);

const now = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
const sq = (v) => (v ? `'${String(v).replace(/'/g, "''")}'` : "NULL");

const out = [];
out.push("-- ════════════════════════════════════════════════════════════════");
out.push("-- seed.sql — generated by scripts/gen-seed.mjs");
out.push(`-- Source: https://www.sports.gov.tw/News/6295 (parsed via ${via})`);
out.push(`-- Records: ${rows.length}`);
out.push("--");
out.push("-- IDs are SHA-256(name|sport|judgment_url) — the same value the");
out.push("-- Worker computes, so the first sync updates these rows in place");
out.push("-- instead of duplicating them.");
out.push("--");
out.push("-- Run: pnpm db:seed");
out.push("-- ════════════════════════════════════════════════════════════════");
out.push("");
out.push("INSERT INTO sync_log (started_at, completed_at, total_fetched, new_records,");
out.push("                      updated_records, removed_records, status, source_url)");
out.push(
  `VALUES ('${now}', '${now}', ${rows.length}, ${rows.length}, 0, 0, 'success',` +
  " 'https://www.sports.gov.tw/News/6295');"
);
out.push("");
out.push("INSERT OR REPLACE INTO coaches");
out.push("  (id, name, sport, category, judgment_url, judgment_type, source_url,");
out.push("   court, case_no, judgment_date, first_seen_at, last_updated_at, is_active)");
out.push("VALUES");

const values = [];
for (const c of rows) {
  const id = await deterministicId(c.name, c.sport, c.judgmentUrl);
  values.push(
    `  ('${id}', ${sq(c.name)}, ${sq(c.sport)}, ${sq(c.category)}, ` +
    `${sq(c.judgmentUrl)}, ${sq(c.judgmentType)}, ${sq(c.sourceUrl)}, ` +
    `${sq(c.court)}, ${sq(c.caseNo)}, ${sq(c.judgmentDate)}, ` +
    `'${now}', '${now}', 1)`
  );
}
out.push(values.join(",\n") + ";");
out.push("");

process.stdout.write(out.join("\n"));
